// layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from './AuthContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "OlympiaBot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {children} {/* Renders the content of the specific page */}
        </AuthProvider>
      </body>
    </html>
  );
}
